language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.0
  - 7.1
  - nightly

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;'

matrix:
  allow_failures:
    - php: nightly

sudo: false

install:
  - if [[ "$BUILD" != true ]]; then
      composer require satooshi/php-coveralls:~0.6@stable;
    fi

before_script:
  - if [[ "$BUILD" != true ]]; then
      mkdir -p build/logs;
      git clone https://github.com/octobercms/october.git october/;
      cd october;
      composer install;
      php artisan october:env;
      sed -i "s/=database/=test/" .env;
      php artisan october:up;
      php artisan plugin:install Lovata.Toolbox;
      PROJECTS_DIR=$(pwd);
      cd ..;
      mkdir -p ./october/plugins/lovata/buddies;
      mv !(october) october/plugins/lovata/buddies;
      ln -s $PROJECTS_DIR"/plugins/lovata/buddies" $PROJECTS_DIR"/tests/fixtures/plugins/lovata/";
      ln -s $PROJECTS_DIR"/plugins/lovata/toolbox" $PROJECTS_DIR"/tests/fixtures/plugins/lovata/";
      cd october/plugins/lovata/buddies;
    fi

script:
  - ../../../vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - if [[ "$BUILD" != true ]]; then
      sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
    fi

jobs:
  include:
    - stage: Release
      env:
        - BUILD=true
      script:
        - NAME="buddies"
        - zip -r $NAME ./ -x .git/\* -x .gitignore -x .travis.yml -x crowdin.yml -x .editorconfig -x .codeclimate.yml -x PHPMD_custom.xml
        - TAG=$(git describe --tags)
        - FILE="./$NAME.zip"
        - if [[ -e $FILE ]]; then
            NEW_NAME="$NAME-$TAG.$TRAVIS_JOB_ID";
            mv $NAME.zip $NEW_NAME.zip;
          fi
      deploy:
        provider: releases
        api_key:
          secure: KTBVuCmtXnUShtFiKkJtxr1Lhmqu2kcSzmsFI85CVqTkQ8Al/f3HR62iqTuqUDojc2WB429CqTDNsCBwLlo6wwE9SOxM9vK31oJ4VLtCcbo7IugQkhXFm2o5SkHazcpuUWoVTdNt5336bxv3gLiV1otZhD0H7zO9PSqv5chXdrOXn/vT6cO8vr89u+if8cRpHcGisOKqWUZcjOEZg7YlrT1oOhbbIW4py3Tq70rQWgd0iDPIdu1E1cqYpJ1gCehjSqHYtPg/chpgpNysRFAB6obH5xo101IORNefmBZD8qFnnH91aH8A9WKAb9tplHJtkSO9c/nUJegd2SGKu0FHM/0wtcGowvFKYCYEKNGWwARDsJ+8HsOlXOcogIAreBdDPOB2ttoH2YBUsGwo0keYC6WBxCvXyoqeY+7iN6iaVbOXVPlSDFsBgG85cSd82hyb1zlu22FefrzKSWvvtGtD8Iqv5XFQ24rwzNuT+NpjOj/rpjxJ3/QKMLp+7Poh0fDAq8v1yU1Hqb1P7J7kFtVUbHsD6PDVN9ifT5afdzCnhm2Zwi/VGXkux5sJK9BklRGwNBkt/LgLdgnvEhT2/WGIPkK/hzaTjEDx3gYjt5mthWZ1jYahnnLCP4YGo51Pn0XguGCGoK850QgRLz9Kd8aqAgBv53Vym1TjWaDCKtogd7Q=
        file: "$NEW_NAME.zip"
        skip_cleanup: true
        on:
          tags: true
          repo: lovata/oc-buddies-plugin
